# -- Project information -----------------------------------------------------

project = 'sphinx-demo'
copyright = '2022, Markus Schmidt'
author = 'Markus Schmidt'


# -- General configuration ---------------------------------------------------

extensions = [
    'myst_parser'
]

# The suffix(es) of source filenames.
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = None

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

html_title = 'sphinx-demo'

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    'logo_only' : True
}
html_context = {
  'display_github': True,
  'github_user': 'mschmidt101010',
  'github_repo': 'sphinx-demo',
  'github_version': 'main/sphinx-docs/docs/'
}