# Workflow for deploying sphinx documentation folder to GitHub Pages
name: Deploy sphinx-docs to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install requirements and build docs
        working-directory: sphinx-docs
        run: |
          sudo apt-get update
          sudo apt-get -y install pip
          pip install -r requirements.txt
          make clean html

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./sphinx-docs/_build/html/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1